### ISSUE TITLE
Couple items I noticed

### ISSUE THREAD

**Issue by klaypigeon** [jdhitsolutions/ADReportingTools#23]
I have had a few issues right off the rip. Just wanted to report up. PS Version : 5.1.17763.1490

```
PS C:\Windows\system32> show-domaintree
This command should be run in a PowerShell Console host.
```

**Comment by jdhitsolutions** [comment]
Are you running in a native PowerShell console or Windows Terminal, or using something else? I'm going to move the `New-ADChangeReport` bug to a new issue since I can duplicate that.

**Comment by jdhitsolutions** [comment]
What do you get when you run `$host.name` ?

**Comment by jdhitsolutions** [comment]
The 'Show-DomainTree` command doesn't work in the ISE because of the ANSI formatting. I might need to enhance the warning message and help to make that clear.

**Comment by jdhitsolutions** [comment]
v1.2.0 will have a clearer warning message and the help documentation also makes it clear this won't run in the PowerShell ISE or VSCode.
