### ISSUE TITLE
Module commands not exported

### ISSUE THREAD

**Issue by jwatson3d** [jdhitsolutions/ADReportingTools#28]
I have tried installing with Install-Module as well as locally via download yet the ExportedCommands list is empty. I have also tried using 

```
Test-ModuleManifest -Path "C:\Program Files\WindowsPowerShell\Modules\ADReportingTools\1.3.0\ADR
eportingTools.psd1"
```

This DOES report the exported commands but I cannot seem to get the modules to work. Am I missing something obvious?

![ADReportingTools-1 3 0_2021-06-21](https://user-images.githubusercontent.com/1030403/122809454-bf832300-d293-11eb-87e2-c28d6923bdf6.png)

**Comment by jdhitsolutions** [comment]
Do you see commands when you run: `Get-Command -module ADReportingTools`. I can't think of a reason you would have a problem. Can you install other modules from the PowerShell Gallery? Try PSScripttools which is another one of my modules.

**Comment by jdhitsolutions** [comment]
Also try `Import-module ADReportingTools -force -verbose`

**Comment by jwatson3d** [comment]
Thank you for responding and trying to help! I was able to successfully install PSScript tools. I then tried using the notes from its README to remove and reinstall ADReportingTools but I get the results.

![ADReportingTools-1 3 0_Reinstall_2021-06-21](https://user-images.githubusercontent.com/1030403/122822827-36281c80-d2a4-11eb-8825-01b94c9cc429.png)

**Comment by jwatson3d** [comment]
Also, RSAT is installed and it does work:

![2021-06-21_15-24-43](https://user-images.githubusercontent.com/1030403/122823434-f9105a00-d2a4-11eb-8275-3c3a7b55ed4e.png)

**Comment by jdhitsolutions** [comment]
That is not all of the verbose output I would expect. Is this Windows 10?

**Comment by jwatson3d** [comment]
PS C:\Windows\system32> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
6      3      9600   0


PS C:\Windows\system32> (Get-WmiObject -class Win32_OperatingSystem).Caption
Microsoft Windows Server 2012 R2 Standard

**Comment by jdhitsolutions** [comment]
Ahhhh....I will have to test that combination. I can't think of a reason it shouldn't work, but the module was built and designed to be run from a Windows 10 desktop, using RSAT command and PowerShell remoting. I'll have to dig deeper.

**Comment by jdhitsolutions** [comment]
I think I found the problem. There has been a long-standing bug when exporting a variable in a module, which I am doing. The manifest setting doesn't work so you need to use Export-ModuleMember in the psm1 file. On newer 5.1 builds, you can export functions in the manifest and variables using Export-ModuleMember. But not on the old version you are running. 

You would need to edit the .psm1 file and change the end to look like this:

```powershell
$FunctionsToExport = 'Show-DomainTree','Get-ADUserAudit','Get-ADSummary','Get-ADFSMO','Get-ADSiteSummary','Get-ADSiteDetail',
'Get-ADGroupUser','Get-ADBranch','Get-ADDomainControllerHealth','New-ADDomainReport','Get-ADReportingTools','Get-ADCanonicalUser',
'Get-ADUserCategory','Get-ADGroupReport','Split-DistinguishedName','New-ADChangeReport',
'Get-ADReportingToolsOptions','Set-ADReportingToolsOptions','Get-ADDepartment','Get-ADComputerReport', 'Get-NTDSInfo',
'Get-ADBackupStatus','Open-ADReportingToolsHelp','New-ADGroupReport','Get-ADManager'
Export-ModuleMember -function $FunctionsToExport -Variable ADUserReportingConfiguration, ADReportingToolsOptions, ADReportingDepartments
```
Even then I wouldn't recommend running this module on Windows Server 2012R2 because there is no ANSI support and many of the commands will look odd.

**Comment by jwatson3d** [comment]
Thank you Jeff, this works on Windows Server 2012R2...

![ADReportingTools-Win2012R2_2021-06-21](https://user-images.githubusercontent.com/1030403/122832622-41ce1000-d2b1-11eb-9316-4ae731ac6297.png)

Get-ADReportingTools lists the tools, albeit with strange ANSI chars...

![Get-ADReportingTools_Win2012R2_2021-06-21](https://user-images.githubusercontent.com/1030403/122832662-4f839580-d2b1-11eb-8466-571e3529f3d0.png)

**Comment by jwatson3d** [comment]
The use case of an Admin with a Win 10 domain-connected machine is likely the most widely used audience. For managing multiple, isolated and secure environments where one wouldn't put Win 10 machines it works well-enough with this work around.

**Comment by jdhitsolutions** [comment]
And you are seeing the ANSI escape sequences because the version of PowerShell you are running doesn't support ANSI.
